name: Tropic
main: me.simplex.tropic.Tropic
version: 0.0.2
website: http://over9000.eu
author: simplex
load: startup
description: WGEN Plugin for Bukkit
commands:
  tropic:
    aliases: [t,trpc]
    description: Generates a new Tropic-World and ports you into it
    usage: /<command> [worldname] [seed]
permissions:
  tropic.*:
    description: Gives access to the /tropic command
    children:
      canyon.command: true
  tropic.command:
    default: op
    description: gives access to the /tropic command